# Dotfiles & Config Sessions

[[session]]
name = "dotfiles ⚙️"
path = "~/.dotfiles"
windows = ["lazygit"]
preview_command = "eza --tree --level=2 --icons --color=always {}"

[[session]]
name = "Ghostty config 👻"
path = "~/.dotfiles/.config/ghostty/"
startup_command = "nvim config"
preview_command = "bat --language=ini --style=snip --color=always ~/.dotfiles/.config/ghostty/config"

[[session]]
name = "neovim config 📦"
path = "~/.dotfiles/.config/nvim"
preview_command = "eza --tree --level=2 --icons --color=always {}"

[[session]]
name = "sesh config 🔗"
path = "~/.dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --language=toml --style=snip --color=always ~/.dotfiles/.config/sesh/sesh.toml"

[[session]]
name = "tmux config 🖥️"
path = "~/.dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --language=bash --style=snip --color=always ~/.dotfiles/.config/tmux/tmux.conf"

[[session]]
name = "lazygit config 🦥"
path = "~/.dotfiles/.config/lazygit"
startup_command = "nvim config.yml"
preview_command = "bat --language=yaml --style=snip --color=always ~/.dotfiles/.config/lazygit/config.yml"

[[session]]
name = "starship config ⭐"
path = "~/.dotfiles/.config"
startup_command = "nvim starship.toml"
preview_command = "bat --language=toml --style=snip --color=always ~/.dotfiles/.config/starship.toml"

[[session]]
name = "/etc/hosts 🌐"
path = "/etc"
startup_command = "sudo nvim hosts"

[[session]]
name = "karabiner config ⌨️"
path = "~/.dotfiles/.config/karabiner"
preview_command = "bat --language=json --style=snip --color=always ~/.dotfiles/.config/karabiner/karabiner.json"
