# Personal Sessions

[[session]]
name = "Home 🏠"
path = "~/"
disable_startup_command = true

[[session]]
name = "Obsidian 🧠"
path = "~/obsidian-vault-kriscard/"
windows = ["lazygit"]

[[session]]
name = "Skills 🤖"
path = "~/projects/Skills/"
windows = ["lazygit"]

[[session]]
name = "Playground 🧪"
path = "~/projects/playground/"

[[session]]
name = "Chris blog ✍️"
path = "~/projects/christophercardoso.dev/"
windows = ["lazygit"]

[[session]]
name = "Markly 👨‍💻"
path = "~/projects/markly/"
windows = ["lazygit"]

[[session]]
name = "Projects 📂"
path = "~/projects/"
disable_startup_command = true
