return {
	"github/copilot.vim",
	cmd = "Copilot",
	event = "InsertEnter",
	keys = {
		{
			"<C-e>",
			'copilot#Accept("<CR>")',
			mode = "i",
			desc = "Accept Copilot suggestion",
			expr = true,
			silent = true,
			noremap = true,
			replace_keycodes = false,
		},
		{
			"<C-j>",
			"copilot#NextSuggestion()",
			mode = "i",
			desc = "Next Copilot suggestion",
			expr = true,
			silent = true,
			noremap = true,
			replace_keycodes = false,
		},
		{
			"<C-k>",
			"copilot#PrevSuggestion()",
			mode = "i",
			desc = "Previous Copilot suggestion",
			expr = true,
			silent = true,
			noremap = true,
			replace_keycodes = false,
		},
	},
	lazy = false,
	config = function()
		vim.g.copilot_no_tab_map = true
		vim.g.copilot_filetypes = {
			["astro"] = true,
			["c"] = true,
			["css"] = true,
			["dockerfile"] = true,
			["go"] = true,
			["graphql"] = true,
			["html"] = true,
			["javascript"] = true,
			["javascriptreact"] = true,
			["json"] = true,
			["kotlin"] = true,
			["lua"] = true,
			["markdown"] = true,
			["ocaml"] = true,
			["php"] = true,
			["python"] = true,
			["ruby"] = true,
			["rust"] = true,
			["scss"] = true,
			["sql"] = true,
			["svelte"] = true,
			["toml"] = true,
			["typescript"] = true,
			["typescriptreact"] = true,
			["vue"] = true,
			["yaml"] = true,
		}
	end,
}
